FROM mcr.microsoft.com/dotnet/framework/sdk:4.8 AS build
WORKDIR /app
COPY wcfapp/WcfServiceWebApp/. .
RUN msbuild /p:Configuration=Release

# Find the ngen.exe path dynamically and use it to precompile the DLL
RUN C:\Windows\Microsoft.NET\Framework\v4.0.30319\ngen.exe install bin\WcfServiceWebApp.dll 

FROM mcr.microsoft.com/dotnet/framework/wcf:4.8 AS runtime
WORKDIR /inetpub/wwwroot
COPY --from=build /app/ .
COPY wcfapp/start-and-monitor.ps1 C:\\start-and-monitor.ps1

ENTRYPOINT ["powershell.exe", "C:\\start-and-monitor.ps1"]
