name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Adjust to your main branch if necessary
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PUSH_TOKEN }}  # Use a GitHub token with repo scope

      - name: Build Docker Image
        run: |
          docker build -f wcfapp/dockerfile.web -t ghcr.io/${{ github.repository_owner }}/wcfservice-docker/wcfservice:latest .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/wcfservice-docker/wcfservice:latest
